

-- Autor: Monica Pellegrini. Fecha: 23.11.2016

VARIABLE FECHA_DESDE VARCHAR2(15);
VARIABLE FECHA_HASTA VARCHAR2(15);
VARIABLE MASCARA     VARCHAR2(15);
VARIABLE TR_HR       VARCHAR2(4);

EXEC :FECHA_DESDE := '&1';
EXEC :FECHA_HASTA := '&2';
EXEC :MASCARA     := 'DD.MM.YYYY';

 --CALLING TRAFFIC
 
DELETE FROM SVA_ZTE_TRAFFIC_ISABHW
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400;

COMMIT;

INSERT INTO SVA_ZTE_TRAFFIC_ISABHW 
SELECT FECHA,
       AREA_CODE,
       COS,
       TOTAL_CALL_COUNT,
       TOTAL_CALL_DURATION,
       TOTAL_GUEST_ACCESS,
       GUEST_ACCESS_DURATION,
       SUBSCRIBER_ACCESS,
       SUBSCRIBER_ACCESS_DURATION,
       COM_ACCESS_FAIL_MAILBOX,
       COM_ACCESS_FAIL_MAILBOX_DUR,
       OUTGOING_CALL,
       OUTGOING_CALL_DURATION,
       PAIS
  FROM (
SELECT TO_DATE(:FECHA_DESDE, 'DD.MM.YYYY')           FECHA,
       AREA_CODE,
       COS,
       TOTAL_CALL_COUNT,
       TOTAL_CALL_DURATION,
       TOTAL_GUEST_ACCESS,
       GUEST_ACCESS_DURATION,
       SUBSCRIBER_ACCESS,
       SUBSCRIBER_ACCESS_DURATION,
       COM_ACCESS_FAIL_MAILBOX,
       COM_ACCESS_FAIL_MAILBOX_DUR,
       OUTGOING_CALL,
       OUTGOING_CALL_DURATION,
       PAIS,
       ROW_NUMBER() OVER(ORDER BY TOTAL_CALL_COUNT DESC) ORDEN
  FROM SVA_ZTE_TRAFFIC_BH
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400
       )
WHERE ORDEN <= 3;

COMMIT;

-- MAILBOX

DELETE FROM SVA_ZTE_MAILBOX_COUNT_DAYW
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400;

COMMIT;

INSERT INTO SVA_ZTE_MAILBOX_COUNT_DAYW  
SELECT TO_DATE(:FECHA_DESDE, 'DD.MM.YYYY')                     FECHA,
       AREA_CODE,
       COS,
       SUM(TOTAL_MAILBOX_COUNT )                               TOTAL_MAILBOX_COUNT,
       SUM(ACTIVE_MAILBOX_COUNT )                              ACTIVE_MAILBOX_COUNT,
       SUM(UN_INITIALIZED_MAILBOX_COUNT )                      UN_INITIALIZED_MAILBOX_COUNT,
       SUM(INITIALIZED_MAILBOX_COUNT )                         INITIALIZED_MAILBOX_COUNT,
       SUM(MAILBX_WITH_SPECIAL_GREETING )                      MAILBX_WITH_SPECIAL_GREETING,
       SUM(MAILBX_WITH_PERSONAL_GREETING )                     MAILBX_WITH_PERSONAL_GREETING,
       SUM(MAILBX_WITH_VOICE_SIGNATURE )                       MAILBX_WITH_VOICE_SIGNATURE,
       SUM(MAILBX_WITH_PASSWORD_CHECK )                        MAILBX_WITH_PASSWORD_CHECK,
       SUM(MAILBX_WITH_NOEMPTY_MAIL_LIST )                     MAILBX_WITH_NOEMPTY_MAIL_LIST,
       SUM(MAIL_LIST_COUNT )                                   MAIL_LIST_COUNT,
       SUM(RECEIVER_COUNT_IN_MAIL_LIST)                        RECEIVER_COUNT_IN_MAIL_LIST,
       PAIS
  FROM SVA_ZTE_MAILBOX_COUNT_DAY
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400
 GROUP BY  AREA_CODE, COS, PAIS;

COMMIT;

-- GUEST DEPOSIT MESSAGE

DELETE FROM SVA_ZTE_DEPOSIT_MESSAGE_ISABHW
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400;

COMMIT;

INSERT INTO SVA_ZTE_DEPOSIT_MESSAGE_ISABHW
SELECT FECHA,
       AREA_CODE,
       COS,
       GUEST_DEPOSIT_MAIL,
       GUEST_DEPOSIT_MAIL_DURATION,
       GUEST_RECORD_EMPTY_MSG,
       GUEST_RECORD_MSG_SUCCESS,
       GUEST_RECORD_MSG_FAILURE,
       GUEST_ADD_RECORDING,
       GUEST_ADD_RECORDING_DURATION,
       GUEST_DEPOSIT_FUT_DELIV_MAIL,
       NODEPOSIT_FOR_BOX_NOT_EXIST,
       NODEPOSIT_FOR_BOX_FULL,
       NODEPOSIT_FOR_BOX_INACTIVE,
       PAIS
  FROM (
SELECT TO_DATE(:FECHA_DESDE, 'DD.MM.YYYY')         FECHA,
       AREA_CODE,
       COS,
       GUEST_DEPOSIT_MAIL,
       GUEST_DEPOSIT_MAIL_DURATION,
       GUEST_RECORD_EMPTY_MSG,
       GUEST_RECORD_MSG_SUCCESS,
       GUEST_RECORD_MSG_FAILURE,
       GUEST_ADD_RECORDING,
       GUEST_ADD_RECORDING_DURATION,
       GUEST_DEPOSIT_FUT_DELIV_MAIL,
       NODEPOSIT_FOR_BOX_NOT_EXIST,
       NODEPOSIT_FOR_BOX_FULL,
       NODEPOSIT_FOR_BOX_INACTIVE,
       PAIS,
       ROW_NUMBER() OVER(ORDER BY GUEST_DEPOSIT_MAIL DESC) ORDEN
  FROM SVA_ZTE_DEPOSIT_MESSAGE_BH
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400
       )
WHERE ORDEN <= 3;

COMMIT;

--MAILBOX PROVITIONING

DELETE FROM SVA_ZTE_PROVISIONING_ISABHW
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400;

COMMIT;

INSERT INTO SVA_ZTE_PROVISIONING_ISABHW
SELECT  FECHA,
        AREA_CODE,
        COS,
        CHANNEL,
        CREATION_COUNT,
        CREATION_SUCCESS_COUNT,
        CREATION_FAILURE_COUNT,
        DELETION_COUNT,
        DELETION_SUCCESS_COUNT,
        DELETION_FAILURE_COUNT,
        MODIFICATION_COUNT,
        MODIFICATION_SUCCESS_COUNT,
        MODIFICATION_FAILURE_COUNT,
        PAIS   
  FROM(
SELECT TO_DATE(:FECHA_DESDE, 'DD.MM.YYYY')      FECHA,
       AREA_CODE,
       COS,
       CHANNEL,
       CREATION_COUNT,
       CREATION_SUCCESS_COUNT,
       CREATION_FAILURE_COUNT,
       DELETION_COUNT,
       DELETION_SUCCESS_COUNT,
       DELETION_FAILURE_COUNT,
       MODIFICATION_COUNT,
       MODIFICATION_SUCCESS_COUNT,
       MODIFICATION_FAILURE_COUNT,
       PAIS,
       ROW_NUMBER() OVER(ORDER BY CREATION_COUNT DESC) ORDEN
  FROM SVA_ZTE_PROVISIONING_BH
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400
       )
 WHERE ORDEN <= 3  ;
 
COMMIT;

--- MCA FORWARD REASON

DELETE FROM SVA_ZTE_MCA_FWD_ISABHW 
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400;

COMMIT;

INSERT INTO SVA_ZTE_MCA_FWD_ISABHW  
SELECT FECHA,
       AREA_CODE,
       COS,
       TOTAL_MISSING_CALL_COUNT,
       B_NOT_ANSWER_COUNT,
       B_BUSY_COUNT,
       B_UNREACHABLE_COUNT,
       OTHER_CALL_COUNT,
       PAIS
  FROM (
SELECT TO_DATE(:FECHA_DESDE, 'DD.MM.YYYY')          FECHA,
       AREA_CODE,
       COS,
       TOTAL_MISSING_CALL_COUNT,
       B_NOT_ANSWER_COUNT,
       B_BUSY_COUNT,
       B_UNREACHABLE_COUNT,
       OTHER_CALL_COUNT,
       PAIS,
       ROW_NUMBER() OVER(ORDER BY TOTAL_MISSING_CALL_COUNT DESC) ORDEN
  FROM SVA_ZTE_MCA_FWD_BH
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400
       )
 WHERE ORDEN <= 3;

COMMIT;

---RETRIEVE MESSAGE

DELETE FROM  SVA_ZTE_RETRIEVE_MESSAGE_IBHW
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400;

COMMIT;

INSERT INTO SVA_ZTE_RETRIEVE_MESSAGE_IBHW 
SELECT FECHA,
       AREA_CODE,
       COS,
       CHANNEL,
       RETRIEVE_NEW_MAIL_COUNT,
       RETRIEVE_HEARD_MAIL_COUNT,
       RETRIEVE_MAIL_FAIL,
       DELETE_MAIL_COUNT,
       SAVE_MAIL_COUNT,
       PAIS
  FROM (
SELECT TO_DATE(:FECHA_DESDE, 'DD.MM.YYYY')          FECHA,
       AREA_CODE,
       COS,
       CHANNEL,
       RETRIEVE_NEW_MAIL_COUNT,
       RETRIEVE_HEARD_MAIL_COUNT,
       RETRIEVE_MAIL_FAIL,
       DELETE_MAIL_COUNT,
       SAVE_MAIL_COUNT,
       PAIS,
       ROW_NUMBER() OVER(ORDER BY RETRIEVE_NEW_MAIL_COUNT DESC) ORDEN
  FROM SVA_ZTE_RETRIEVE_MESSAGE_BH
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399 / 86400
       )
 WHERE ORDEN <= 3;

EXIT;

