
-- AUTOR: MONICA PELLEGRINI. FECHA: 31.03.2016. MOTIVO: SOLITUD DE NUEVAS TABLAS PARA PLATAFORMA OCUDR TEKELEC_OCUDR_UDRFE_PERF_HOUR

MERGE INTO TEKELEC_OCUDR_UDRFE_PERF_RAW A
 USING(SELECT FECHA,
              ALCANCE_TYPE,
              ALCANCE,
              SERVER,
              RX_REQUEST_ALL,
              RX_REQUEST_FAILED_ALL,
              RX_REQUEST_FAILED_PUR,
              RX_REQUEST_FAILED_SNR,
              RX_REQUEST_FAILED_UDR,
              RX_REQ_REJ_MSJ_CODING_FAILED,
              RX_REQ_REJ_UNKNOWN_USER,
              RX_REQUEST_SUCCESS_FUL_ALL,
              RX_REQUEST_SUCCESS_FUL_PUR,
              RX_REQUEST_SUCCESS_FUL_SNR,
              RX_REQUEST_SUCCESS_FUL_UDR,
              RX_RESPONSE_ALL,
              TM_RESPONSE_TIMES_PR,
              TM_UDR_ANSAVGQ,
              TM_UDR_ANS_PEAKQ,
              TM_UDR_AVG_STK_EVENTQ,
              TM_UDRPE_AKS_TK_EVENTQ,
              TM_UDR_REQ_AVGQ,
              TM_UDR_REQ_PEAKQ,
              TX_REQUEST_ALL,
              TX_REQUEST_FAILED_ALL,
              TX_REQUEST_FAILED_PNR,
              TX_REQUEST_SUCCESS_FUL_ALL,
              TX_REQUEST_SUCCESS_FUL_PNR,
              TX_RESPONSE_ALL
         FROM AUX_OCUDR_UDRFE_PERFORMANCE
       WHERE FECHA BETWEEN TO_DATE('&1', 'DD.MM.YYYY')
                       AND TO_DATE('&2', 'DD.MM.YYYY') + 86399/86400
       ORDER BY FECHA
       ) B
       ON(A.FECHA = B.FECHA AND
          A.ALCANCE_TYPE = B.ALCANCE_TYPE AND
          A.ALCANCE = B.ALCANCE AND
          A.SERVER = B.SERVER  )
       WHEN MATCHED THEN UPDATE SET A.RX_REQUEST_ALL                  =   B.RX_REQUEST_ALL                                   ,
                                    A.RX_REQUEST_FAILED_ALL           =   B.RX_REQUEST_FAILED_ALL                            ,
                                    A.RX_REQUEST_FAILED_PUR           =   B.RX_REQUEST_FAILED_PUR                            ,
                                    A.RX_REQUEST_FAILED_SNR           =   B.RX_REQUEST_FAILED_SNR                            ,
                                    A.RX_REQUEST_FAILED_UDR           =   B.RX_REQUEST_FAILED_UDR                            ,
                                    A.RX_REQ_REJ_MSJ_CODING_FAILED    =   B.RX_REQ_REJ_MSJ_CODING_FAILED                     ,
                                    A.RX_REQ_REJ_UNKNOWN_USER         =   B.RX_REQ_REJ_UNKNOWN_USER                          ,
                                    A.RX_REQUEST_SUCCESS_FUL_ALL      =   B.RX_REQUEST_SUCCESS_FUL_ALL                       ,
                                    A.RX_REQUEST_SUCCESS_FUL_PUR      =   B.RX_REQUEST_SUCCESS_FUL_PUR                       ,
                                    A.RX_REQUEST_SUCCESS_FUL_SNR      =   B.RX_REQUEST_SUCCESS_FUL_SNR                       ,
                                    A.RX_REQUEST_SUCCESS_FUL_UDR      =   B.RX_REQUEST_SUCCESS_FUL_UDR                       ,
                                    A.RX_RESPONSE_ALL                 =   B.RX_RESPONSE_ALL                                  ,
                                    A.TM_RESPONSE_TIMES_PR            =   B.TM_RESPONSE_TIMES_PR                             ,
                                    A.TM_UDR_ANSAVGQ                  =   B.TM_UDR_ANSAVGQ                                   ,
                                    A.TM_UDR_ANS_PEAKQ                =   B.TM_UDR_ANS_PEAKQ                                 ,
                                    A.TM_UDR_AVG_STK_EVENTQ           =   B.TM_UDR_AVG_STK_EVENTQ                            ,
                                    A.TM_UDRPE_AKS_TK_EVENTQ          =   B.TM_UDRPE_AKS_TK_EVENTQ                           ,
                                    A.TM_UDR_REQ_AVGQ                 =   B.TM_UDR_REQ_AVGQ                                  ,
                                    A.TM_UDR_REQ_PEAKQ                =   B.TM_UDR_REQ_PEAKQ                                 ,
                                    A.TX_REQUEST_ALL                  =   B.TX_REQUEST_ALL                                   ,
                                    A.TX_REQUEST_FAILED_ALL           =   B.TX_REQUEST_FAILED_ALL                            ,
                                    A.TX_REQUEST_FAILED_PNR           =   B.TX_REQUEST_FAILED_PNR                            ,
                                    A.TX_REQUEST_SUCCESS_FUL_ALL      =   B.TX_REQUEST_SUCCESS_FUL_ALL                       ,
                                    A.TX_REQUEST_SUCCESS_FUL_PNR      =   B.TX_REQUEST_SUCCESS_FUL_PNR                       ,
                                    A.TX_RESPONSE_ALL                 =   B.TX_RESPONSE_ALL
        WHEN NOT MATCHED THEN INSERT (
                                  A.FECHA                         ,
                                  A.ALCANCE_TYPE                  ,
                                  A.ALCANCE                       ,
                                  A.SERVER                        ,
                                  A.RX_REQUEST_ALL                ,
                                  A.RX_REQUEST_FAILED_ALL         ,
                                  A.RX_REQUEST_FAILED_PUR         ,
                                  A.RX_REQUEST_FAILED_SNR         ,
                                  A.RX_REQUEST_FAILED_UDR         ,
                                  A.RX_REQ_REJ_MSJ_CODING_FAILED  ,
                                  A.RX_REQ_REJ_UNKNOWN_USER       ,
                                  A.RX_REQUEST_SUCCESS_FUL_ALL    ,
                                  A.RX_REQUEST_SUCCESS_FUL_PUR    ,
                                  A.RX_REQUEST_SUCCESS_FUL_SNR    ,
                                  A.RX_REQUEST_SUCCESS_FUL_UDR    ,
                                  A.RX_RESPONSE_ALL               ,
                                  A.TM_RESPONSE_TIMES_PR          ,
                                  A.TM_UDR_ANSAVGQ                ,
                                  A.TM_UDR_ANS_PEAKQ              ,
                                  A.TM_UDR_AVG_STK_EVENTQ         ,
                                  A.TM_UDRPE_AKS_TK_EVENTQ        ,
                                  A.TM_UDR_REQ_AVGQ               ,
                                  A.TM_UDR_REQ_PEAKQ              ,
                                  A.TX_REQUEST_ALL                ,
                                  A.TX_REQUEST_FAILED_ALL         ,
                                  A.TX_REQUEST_FAILED_PNR         ,
                                  A.TX_REQUEST_SUCCESS_FUL_ALL    ,
                                  A.TX_REQUEST_SUCCESS_FUL_PNR    ,
                                  A.TX_RESPONSE_ALL
                                    )
                            VALUES (
                                  B.FECHA                         ,
                                  B.ALCANCE_TYPE                  ,
                                  B.ALCANCE                       ,
                                  B.SERVER                        ,
                                  B.RX_REQUEST_ALL                ,
                                  B.RX_REQUEST_FAILED_ALL         ,
                                  B.RX_REQUEST_FAILED_PUR         ,
                                  B.RX_REQUEST_FAILED_SNR         ,
                                  B.RX_REQUEST_FAILED_UDR         ,
                                  B.RX_REQ_REJ_MSJ_CODING_FAILED  ,
                                  B.RX_REQ_REJ_UNKNOWN_USER       ,
                                  B.RX_REQUEST_SUCCESS_FUL_ALL    ,
                                  B.RX_REQUEST_SUCCESS_FUL_PUR    ,
                                  B.RX_REQUEST_SUCCESS_FUL_SNR    ,
                                  B.RX_REQUEST_SUCCESS_FUL_UDR    ,
                                  B.RX_RESPONSE_ALL               ,
                                  B.TM_RESPONSE_TIMES_PR          ,
                                  B.TM_UDR_ANSAVGQ                ,
                                  B.TM_UDR_ANS_PEAKQ              ,
                                  B.TM_UDR_AVG_STK_EVENTQ         ,
                                  B.TM_UDRPE_AKS_TK_EVENTQ        ,
                                  B.TM_UDR_REQ_AVGQ               ,
                                  B.TM_UDR_REQ_PEAKQ              ,
                                  B.TX_REQUEST_ALL                ,
                                  B.TX_REQUEST_FAILED_ALL         ,
                                  B.TX_REQUEST_FAILED_PNR         ,
                                  B.TX_REQUEST_SUCCESS_FUL_ALL    ,
                                  B.TX_REQUEST_SUCCESS_FUL_PNR    ,
                                  B.TX_RESPONSE_ALL
                                    );
 COMMIT;
 EXIT;

