
-- Autor: Monica Pellegrini. Fecha:29.11.2016

VARIABLE FECHA_DESDE VARCHAR2(15);
VARIABLE FECHA_HASTA  VARCHAR2(15);

EXEC :FECHA_DESDE := '&1';
EXEC :FECHA_HASTA := '&2';

BEGIN

P_TEKELEC_OCUDR_OAM_ISABHW(P_FECHA_DESDE => :FECHA_DESDE,
                           P_FECHA_HASTA => :FECHA_HASTA);
                          
P_TEKELEC_OCUDR_PROV_ISABHW(P_FECHA_DESDE => :FECHA_DESDE,
                            P_FECHA_HASTA => :FECHA_HASTA);
                              
P_TEKELEC_OCUDR_SH_PERF_ISABHW(P_FECHA_DESDE => :FECHA_DESDE,
                               P_FECHA_HASTA => :FECHA_HASTA);

P_TEKELEC_OCUDR_UDRBE_ISABHW(P_FECHA_DESDE => :FECHA_DESDE,
                             P_FECHA_HASTA => :FECHA_HASTA);

END;
/
EXIT;
