-- Autor: Mario Heredia. Fecha: 20.06.2017.
-- Actualizacion: Mario Heredia. Fecha: 03.07.2017. Motivo: Implementacion de Paquete.

DECLARE

CURSOR FECHAS (PSEDSD IN CHAR, PSEDSA IN CHAR, PSEDSL IN NUMBER) IS
SELECT TO_CHAR(DECODE(HTSAEFHN, HTSAEFHM, HTSAEFHE, HTSAEFHE + ((HTSAEFHN - 1) * PSEDSL / 24)       ), 'DD.MM.YYYY HH24') FECHA_DESDE,
       TO_CHAR(DECODE(HTSAEFHN, HTSAEFHX, HTSAEFHA, HTSAEFHE + ((HTSAEFHN)     * PSEDSL / 24) - 1/24), 'DD.MM.YYYY HH24') FECHA_HASTA
  FROM (
SELECT TO_DATE(PSEDSD, 'DD.MM.YYYY HH24') HTSAEFHE,
       TO_DATE(PSEDSA, 'DD.MM.YYYY HH24') HTSAEFHA,
       MAX(LEVEL) OVER() HTSAEFHX,
       MIN(LEVEL) OVER() HTSAEFHM,
       LEVEL HTSAEFHN
  FROM DUAL CONNECT BY LEVEL <=
       (
SELECT FLOOR(((HTSAEFHD * 24) + HTSAEFHH) / PSEDSL) + DECODE(MOD((HTSAEFHD * 24) + HTSAEFHH, PSEDSL), 0, 0, 1) HTSAEFHV
  FROM (
SELECT FLOOR(HTSAEFHA - HTSAEFHE) HTSAEFHD, ROUND(MOD(HTSAEFHA - HTSAEFHE, FLOOR(HTSAEFHA - HTSAEFHE)) / (1/24), 0) HTSAEFHH
  FROM (
SELECT TO_DATE(PSEDSD, 'DD.MM.YYYY HH24') HTSAEFHE,
       TO_DATE(PSEDSA, 'DD.MM.YYYY HH24') HTSAEFHA
  FROM DUAL
       )
       )
       )
       )
 ORDER BY HTSAEFHN DESC;

CURSOR ELEMENTOS IS
SELECT '&RC' RC FROM DUAL;

V_FECHA_DESDE VARCHAR2(15);
V_FECHA_HASTA VARCHAR2(15);

C_CICLO       NUMBER := 281;
V_CICLO       NUMBER;

BEGIN

  SELECT '&1' /*'DD.MM.YYYY HH24'*/ FECHA_DESDE,
         '&2' /*'DD.MM.YYYY HH24'*/ FECHA_HASTA,
         PRM_VALUE
    INTO V_FECHA_DESDE,
         V_FECHA_HASTA,
         V_CICLO
    FROM CALIDAD_PARAMETROS
   WHERE PRM_ID = C_CICLO;

  FOR SEN IN ELEMENTOS LOOP

      FOR SYN IN FECHAS (V_FECHA_DESDE, V_FECHA_HASTA, V_CICLO) LOOP

          G_TABLERONQIHOUR.P_AUX_TABLERO_NQI_HOUR_INS (SEN.RC, SYN.FECHA_DESDE, SYN.FECHA_HASTA);

          G_TABLERONQIHOUR.P_TABLERO_NQI_HOUR_INS (SEN.RC, SYN.FECHA_DESDE, SYN.FECHA_HASTA);

      END LOOP;

  END LOOP;

END;
/
