
-- Autor: Monica Pellegrini. Fecha:24.10.2016

VARIABLE FECHA_DESDE VARCHAR2(15);
VARIABLE FECHA_HASTA  VARCHAR2(15);

EXEC :FECHA_DESDE := '&1 &2';
EXEC :FECHA_HASTA := '&3 &4';

BEGIN

P_LTE_NSN_QDA_QDR_HOUR_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                             P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_RETENTION_RC5_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                              P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_RETENTION_RC3_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                              P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_RETENTION_RC2_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                              P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_RETENTION_RC1_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                              P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_QDE_RC5_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                        P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_QDE_RC3_INS( P_FECHA_DESDE => :FECHA_DESDE,
                       P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_QDE_RC2_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                       P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_QDE_RC1_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                        P_FECHA_HASTA => :FECHA_HASTA);

P_LTE_NSN_WEIGH_AVAIL_INS ( P_FECHA_DESDE => :FECHA_DESDE,
                            P_FECHA_HASTA => :FECHA_HASTA);

END;
/
EXIT;

