--Actualizacion 19/07/2010 - Mauro Arraigada
--Se modifica el DATA_THR2 para que traiga de MACD.
DELETE FROM AMX_INDICADORES
 WHERE ID_REGISTRO LIKE TO_CHAR(TO_DATE('&1', 'DD.MM.YYYY'), 'YYYYMM')||'%'
   AND ID_TECNOLOGIA = 2;

COMMIT;

INSERT INTO AMX_INDICADORES
(
  PK_ID_CVECALIDAD,
  ID_REGISTRO,
  ID_TECNOLOGIA,
  VOICE_INACC,
  VOICE_NONRET,
  VOICE_SPEECHQUALITY,
  VOICE_TRAFFIC,
  DATA_INACC,
  DATA_NONRET,
  DATA_THR1,
  DATA_THR2,
  DATA_TRAFFIC
)
SELECT ROW_NUMBER () OVER(ORDER BY A.ID_REGISTRO ASC) PK_ID_CVECALIDAD,
       A.ID_REGISTRO,
       A.ID_TECNOLOGIA,
       VOICE_INACC,
       VOICE_NONRET,
       VOICE_SPEECHQUALITY,
       VOICE_TRAFFIC,
       DATA_INACC,
       DATA_NON_RET,
       DATA_THR1,
       DATA_THR2,
       DATA_TRAFFIC
  FROM (
SELECT TO_CHAR(FECHA, 'YYYYMM')||DECODE(MERCADO, 'Argentina', 3, 'Uruguay', 5, 'Paraguay', 4) ID_REGISTRO,
       2 ID_TECNOLOGIA,
       100 - ACCESSIBILITY_VOICE VOICE_INACC,
       RAB_DROP_VOICE VOICE_NONRET,
       BLER_VOICE_UL VOICE_SPEECHQUALITY
  FROM TABLERO_UMTS_REGION_MONTH
 WHERE FECHA = TO_DATE('&1', 'DD.MM.YYYY')
   AND SUMMARY = 'ISABH_MONTH'
   AND REGION = 'PAIS'
       ) A,
       (
SELECT TO_CHAR(FECHA, 'YYYYMM')||DECODE(MERCADO, 'Argentina', 3, 'Uruguay', 5, 'Paraguay', 4) ID_REGISTRO,
       2 ID_TECNOLOGIA,
       100 - ACCESSIBILITY_PACKET DATA_INACC,
       RAB_DROP_PACKET DATA_NON_RET,
       R99_DL_PS_THROUGHPUT_SDU_KBPS DATA_THR1,
       THROUGHPUT_HSDPA_MACD DATA_THR2 --THROUGHPUT_HSDPA_MACD
  FROM TABLERO_UMTS_REGION_MONTH
 WHERE FECHA = TO_DATE('&1', 'DD.MM.YYYY')
   AND SUMMARY = 'ISABH_MONTH'
   AND REGION = 'PAIS'
       ) B,
       (
SELECT TO_CHAR(FECHA, 'YYYYMM')||DECODE(PAIS, 'Argentina', 3, 'Uruguay', 5, 'Paraguay', 4) ID_REGISTRO,
       2 ID_TECNOLOGIA,
       CS_ERL VOICE_TRAFFIC
  FROM UMTS_NSN_SERVICE_PAIS_ISABHMC
 WHERE FECHA = TO_DATE('&1','DD.MM.YYYY')
       ) C,
       (
SELECT TO_CHAR(FECHA, 'YYYYMM')||DECODE(MERCADO, 'Argentina', 3, 'Uruguay', 5, 'Paraguay', 4) ID_REGISTRO,
       2 ID_TECNOLOGIA,
       (HSDPA_DATA_DL_MBYTES + UMTS_PS_DATA_DL_MBYTES) /1024 DATA_TRAFFIC
  FROM TABLERO_MOUS_DAYM
 WHERE FECHA = TO_DATE('&1','DD.MM.YYYY')
   AND REGION = 'PAIS'
       ) D
 WHERE A.ID_REGISTRO = B.ID_REGISTRO (+)
   AND A.ID_REGISTRO = C.ID_REGISTRO (+)
   AND A.ID_REGISTRO = D.ID_REGISTRO (+);

COMMIT;

EXIT;

