--TAB=AVAILABILITY
WITH RFC AS  (SELECT FECHA
                 FROM CALIDAD_STATUS_REFERENCES
                WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                                AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
              ),
RC as (SELECT FECHA,
      COUNT(1) CANTIDAD,
      OSSRC
FROM LTE_NSN_AVAIL_LCEL_DAY
WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
GROUP BY FECHA, OSSRC),
RC2 AS (SELECT FECHA,
    DECODE(OSSRC, 'OSSRC5', CANTIDAD) OSSRC5_CANTIDAD,
    DECODE(OSSRC, 'OSSRC3', CANTIDAD) OSSRC3_CANTIDAD,
    DECODE(OSSRC, 'OSSRC2', CANTIDAD) OSSRC2_CANTIDAD
FROM RC),
RC3 AS (SELECT FECHA,
       MAX(OSSRC5_CANTIDAD) OSSRC5_CANTIDAD,
       MAX(OSSRC3_CANTIDAD) OSSRC3_CANTIDAD,
       MAX(OSSRC2_CANTIDAD) OSSRC2_CANTIDAD
       FROM RC2
       GROUP BY FECHA),
SUM1 AS (SELECT FECHA,
      COUNT(1) CANTIDAD,
      ELEMENT_CLASS
      FROM LTE_NSN_AVAIL_NE_DAY
      WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                      AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
      GROUP BY FECHA, ELEMENT_CLASS),
SUM2 AS(SELECT FECHA,
      DECODE(ELEMENT_CLASS, 'LNBTS',   CANTIDAD) LNBTS_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'CIUDAD',  CANTIDAD) CIUDAD_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'ALM',     CANTIDAD) ALM_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'MERCADO', CANTIDAD) MERCADO_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'PAIS',    CANTIDAD) PAIS_CANTIDAD
FROM SUM1),
SUM3 AS (SELECT FECHA,
       MAX(LNBTS_CANTIDAD) LNBTS_CANTIDAD,
       MAX(CIUDAD_CANTIDAD) CIUDAD_CANTIDAD,
       MAX(ALM_CANTIDAD) ALM_CANTIDAD,
       MAX(MERCADO_CANTIDAD) MERCADO_CANTIDAD,
       MAX(PAIS_CANTIDAD) PAIS_CANTIDAD
       FROM SUM2
       GROUP BY FECHA)
SELECT RFC.FECHA,
       OSSRC2_CANTIDAD OSSRC2,
       OSSRC3_CANTIDAD OSSRC3,
       OSSRC5_CANTIDAD OSSRC5,
       LNBTS_CANTIDAD LNBTS,
       CIUDAD_CANTIDAD CIUDAD,
       ALM_CANTIDAD ALM,
       MERCADO_CANTIDAD MERCADO,
       PAIS_CANTIDAD PAIS
FROM RC3, RFC, SUM3
WHERE RFC.FECHA = RC3.FECHA
      AND RFC.FECHA = SUM3.FECHA
ORDER BY RFC.FECHA
;

--TAB=SERVICE
WITH RFC AS  (SELECT FECHA
                 FROM CALIDAD_STATUS_REFERENCES
                WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                                AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
              ),
RC as (SELECT FECHA,
      COUNT(1) CANTIDAD,
      OSSRC
FROM LTE_NSN_SERVICE_LCEL_DAY
WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
GROUP BY FECHA, OSSRC),
RC2 AS (SELECT FECHA,
    DECODE(OSSRC, 'OSSRC5', CANTIDAD) OSSRC5_CANTIDAD,
    DECODE(OSSRC, 'OSSRC3', CANTIDAD) OSSRC3_CANTIDAD,
    DECODE(OSSRC, 'OSSRC2', CANTIDAD) OSSRC2_CANTIDAD
FROM RC),
RC3 AS (SELECT FECHA,
       MAX(OSSRC5_CANTIDAD) OSSRC5_CANTIDAD,
       MAX(OSSRC3_CANTIDAD) OSSRC3_CANTIDAD,
       MAX(OSSRC2_CANTIDAD) OSSRC2_CANTIDAD
       FROM RC2
       GROUP BY FECHA),
SUM1 AS (SELECT FECHA,
      COUNT(1) CANTIDAD,
      ELEMENT_CLASS
      FROM LTE_NSN_SERVICE_NE_DAY
      WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                      AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
      GROUP BY FECHA, ELEMENT_CLASS),
SUM2 AS(SELECT FECHA,
      DECODE(ELEMENT_CLASS, 'LNBTS',   CANTIDAD) LNBTS_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'CIUDAD',  CANTIDAD) CIUDAD_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'ALM',     CANTIDAD) ALM_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'MERCADO', CANTIDAD) MERCADO_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'PAIS',    CANTIDAD) PAIS_CANTIDAD
FROM SUM1),
SUM3 AS (SELECT FECHA,
       MAX(LNBTS_CANTIDAD) LNBTS_CANTIDAD,
       MAX(CIUDAD_CANTIDAD) CIUDAD_CANTIDAD,
       MAX(ALM_CANTIDAD) ALM_CANTIDAD,
       MAX(MERCADO_CANTIDAD) MERCADO_CANTIDAD,
       MAX(PAIS_CANTIDAD) PAIS_CANTIDAD
       FROM SUM2
       GROUP BY FECHA)
SELECT RFC.FECHA,
       OSSRC2_CANTIDAD OSSRC2,
       OSSRC3_CANTIDAD OSSRC3,
       OSSRC5_CANTIDAD OSSRC5,
       LNBTS_CANTIDAD LNBTS,
       CIUDAD_CANTIDAD CIUDAD,
       ALM_CANTIDAD ALM,
       MERCADO_CANTIDAD MERCADO,
       PAIS_CANTIDAD PAIS
FROM RC3, RFC, SUM3
WHERE RFC.FECHA = RC3.FECHA
      AND RFC.FECHA = SUM3.FECHA
ORDER BY RFC.FECHA
;


--TAB=PAQ
WITH RFC AS  (SELECT FECHA
                 FROM CALIDAD_STATUS_REFERENCES
                WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                                AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
              ),
RC as (SELECT FECHA,
      COUNT(1) CANTIDAD,
      OSSRC
FROM LTE_NSN_PAQ_LCEL_DAY
WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
GROUP BY FECHA, OSSRC),
RC2 AS (SELECT FECHA,
    DECODE(OSSRC, 'OSSRC5', CANTIDAD) OSSRC5_CANTIDAD,
    DECODE(OSSRC, 'OSSRC3', CANTIDAD) OSSRC3_CANTIDAD,
    DECODE(OSSRC, 'OSSRC2', CANTIDAD) OSSRC2_CANTIDAD
FROM RC),
RC3 AS (SELECT FECHA,
       MAX(OSSRC5_CANTIDAD) OSSRC5_CANTIDAD,
       MAX(OSSRC3_CANTIDAD) OSSRC3_CANTIDAD,
       MAX(OSSRC2_CANTIDAD) OSSRC2_CANTIDAD
       FROM RC2
       GROUP BY FECHA),
SUM1 AS (SELECT FECHA,
      COUNT(1) CANTIDAD,
      ELEMENT_CLASS
      FROM LTE_NSN_PAQ_NE_DAY
      WHERE FECHA BETWEEN TO_DATE('&DateFrom', 'DD.MM.YYYY')
                      AND TO_DATE('&DateTo', 'DD.MM.YYYY') + 86399/86400
      GROUP BY FECHA, ELEMENT_CLASS),
SUM2 AS(SELECT FECHA,
      DECODE(ELEMENT_CLASS, 'LNBTS',   CANTIDAD) LNBTS_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'CIUDAD',  CANTIDAD) CIUDAD_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'ALM',     CANTIDAD) ALM_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'MERCADO', CANTIDAD) MERCADO_CANTIDAD,
      DECODE(ELEMENT_CLASS, 'PAIS',    CANTIDAD) PAIS_CANTIDAD
FROM SUM1),
SUM3 AS (SELECT FECHA,
       MAX(LNBTS_CANTIDAD) LNBTS_CANTIDAD,
       MAX(CIUDAD_CANTIDAD) CIUDAD_CANTIDAD,
       MAX(ALM_CANTIDAD) ALM_CANTIDAD,
       MAX(MERCADO_CANTIDAD) MERCADO_CANTIDAD,
       MAX(PAIS_CANTIDAD) PAIS_CANTIDAD
       FROM SUM2
       GROUP BY FECHA)
SELECT RFC.FECHA,
       OSSRC2_CANTIDAD OSSRC2,
       OSSRC3_CANTIDAD OSSRC3,
       OSSRC5_CANTIDAD OSSRC5,
       LNBTS_CANTIDAD LNBTS,
       CIUDAD_CANTIDAD CIUDAD,
       ALM_CANTIDAD ALM,
       MERCADO_CANTIDAD MERCADO,
       PAIS_CANTIDAD PAIS
FROM RC3, RFC, SUM3
WHERE RFC.FECHA = RC3.FECHA
      AND RFC.FECHA = SUM3.FECHA
ORDER BY RFC.FECHA
;




