--LTECOUNTERSHOURLY

--Tab=OSSRC1

SELECT RFC.FECHA,
       AV.CANTIDAD AV_CNT,
       LD.CANTIDAD LD_CNT,
       LT.CANTIDAD LT_CNT,
       PS.CANTIDAD PS_CNT,
       QD.CANTIDAD QD_CNT,
       QU.CANTIDAD QU_CNT,
       RC.CANTIDAD RC_CNT,
       ES.CANTIDAD ES_CNT,
       HO.CANTIDAD HO_CNT
  FROM (
        SELECT FECHA
          FROM CALIDAD_STATUS_REFERENCES
         WHERE FECHA BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                         AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
       ) RFC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELAV_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) AV,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLD_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLT_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LT,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LEPSB_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) PS,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQDL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQUL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QU,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LRRC_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) RC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LUEST_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) ES,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM LTE_C_NSN_ISHO_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC1'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) HO
WHERE RFC.FECHA = AV.FECHA (+)
   AND RFC.FECHA = LD.FECHA (+)
   AND RFC.FECHA = LT.FECHA (+)
   AND RFC.FECHA = PS.FECHA (+)
   AND RFC.FECHA = QD.FECHA (+)
   AND RFC.FECHA = QU.FECHA (+)
   AND RFC.FECHA = RC.FECHA (+)
   AND RFC.FECHA = ES.FECHA (+)
   AND RFC.FECHA = HO.FECHA (+)
ORDER BY RFC.FECHA;

--Tab=OSSRC2

SELECT RFC.FECHA,
       AV.CANTIDAD AV_CNT,
       LD.CANTIDAD LD_CNT,
       LT.CANTIDAD LT_CNT,
       PS.CANTIDAD PS_CNT,
       QD.CANTIDAD QD_CNT,
       QU.CANTIDAD QU_CNT,
       RC.CANTIDAD RC_CNT,
       ES.CANTIDAD ES_CNT,
       HO.CANTIDAD HO_CNT
  FROM (
        SELECT FECHA
          FROM CALIDAD_STATUS_REFERENCES
         WHERE FECHA BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                         AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
       ) RFC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELAV_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) AV,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLD_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLT_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LT,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LEPSB_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) PS,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQDL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQUL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QU,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LRRC_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) RC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LUEST_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) ES,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM LTE_C_NSN_ISHO_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC2'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) HO
WHERE RFC.FECHA = AV.FECHA (+)
   AND RFC.FECHA = LD.FECHA (+)
   AND RFC.FECHA = LT.FECHA (+)
   AND RFC.FECHA = PS.FECHA (+)
   AND RFC.FECHA = QD.FECHA (+)
   AND RFC.FECHA = QU.FECHA (+)
   AND RFC.FECHA = RC.FECHA (+)
   AND RFC.FECHA = ES.FECHA (+)
   AND RFC.FECHA = HO.FECHA (+)
ORDER BY RFC.FECHA;

--Tab=OSSRC3

SELECT RFC.FECHA,
       AV.CANTIDAD AV_CNT,
       LD.CANTIDAD LD_CNT,
       LT.CANTIDAD LT_CNT,
       PS.CANTIDAD PS_CNT,
       QD.CANTIDAD QD_CNT,
       QU.CANTIDAD QU_CNT,
       RC.CANTIDAD RC_CNT,
       ES.CANTIDAD ES_CNT, 
       HO.CANTIDAD HO_CNT
  FROM (
        SELECT FECHA
          FROM CALIDAD_STATUS_REFERENCES
         WHERE FECHA BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                         AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
       ) RFC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELAV_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) AV,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLD_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLT_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LT,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LEPSB_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) PS,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQDL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQUL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QU,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LRRC_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) RC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LUEST_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) ES,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM LTE_C_NSN_ISHO_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC3'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) HO
WHERE RFC.FECHA = AV.FECHA (+)
   AND RFC.FECHA = LD.FECHA (+)
   AND RFC.FECHA = LT.FECHA (+)
   AND RFC.FECHA = PS.FECHA (+)
   AND RFC.FECHA = QD.FECHA (+)
   AND RFC.FECHA = QU.FECHA (+)
   AND RFC.FECHA = RC.FECHA (+)
   AND RFC.FECHA = ES.FECHA (+)
   AND RFC.FECHA = HO.FECHA (+)
ORDER BY RFC.FECHA;

--Tab=OSSRC5

SELECT RFC.FECHA,
       AV.CANTIDAD AV_CNT,
       LD.CANTIDAD LD_CNT,
       LT.CANTIDAD LT_CNT,
       PS.CANTIDAD PS_CNT,
       QD.CANTIDAD QD_CNT,
       QU.CANTIDAD QU_CNT,
       RC.CANTIDAD RC_CNT,
       ES.CANTIDAD ES_CNT,
       HO.CANTIDAD HO_CNT
  FROM (
        SELECT FECHA
          FROM CALIDAD_STATUS_REFERENCES
         WHERE FECHA BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                         AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
       ) RFC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELAV_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) AV,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLD_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LCELLT_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) LT,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LEPSB_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) PS,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQDL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QD,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LPQUL_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) QU,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LRRC_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) RC,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM NOKLTE_PS_LUEST_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
                     AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) ES,
       (
        SELECT TRUNC(R.PERIOD_START_TIME, 'HH24') FECHA, COUNT(*) CANTIDAD
          FROM LTE_C_NSN_ISHO_MNC1_RAW R
         WHERE R.PERIOD_START_TIME BETWEEN TO_DATE('&FD', 'DD.MM.YYYY')
                                       AND TO_DATE('&FH', 'DD.MM.YYYY') + 86399/86400
									   AND OSSRC = 'OSSRC5'
         GROUP BY TRUNC(R.PERIOD_START_TIME, 'HH24')
       ) HO
WHERE RFC.FECHA = AV.FECHA (+)
   AND RFC.FECHA = LD.FECHA (+)
   AND RFC.FECHA = LT.FECHA (+)
   AND RFC.FECHA = PS.FECHA (+)
   AND RFC.FECHA = QD.FECHA (+)
   AND RFC.FECHA = QU.FECHA (+)
   AND RFC.FECHA = RC.FECHA (+)
   AND RFC.FECHA = ES.FECHA (+)
   AND RFC.FECHA = HO.FECHA (+)
ORDER BY RFC.FECHA;
