create or replace PROCEDURE P_LTE_NQI_DAY_INS (P_FECHA_DESDE IN CHAR, P_FECHA_HASTA IN CHAR) IS
-- Autor:  Monica Pellegrin. Fecha:28.06.2016


CURSOR CUR_NQI_DAY (FECHA_DESDE VARCHAR2, FECHA_HASTA VARCHAR2) IS
SELECT A.FECHA, 
       A.LNCEL_ID,
       B.LNCEL_NAME,
       B.LNBTS_ID,
       B.LNBTS_NAME,
       B.OSSRC,
       B.MERCADO,
       B.PAIS,
       SUM(QDA_NUM) QDA_NUM,
       SUM(QDA_DEN) QDA_DEN,        
       SUM(QDR_NUM) QDR_NUM,
       SUM(QDR_DEN) QDR_DEN
 FROM(
SELECT FECHA, 
       LNCEL_ID,
       ACCESIBILITY,
       RETAINABILITY,
       CASE WHEN ACCESIBILITY < 99 THEN 0
                               ELSE QDA_ATTEMPTS END QDA_NUM,
                               QDA_ATTEMPTS QDA_DEN,
       CASE WHEN RETAINABILITY < 99 THEN 0
                                ELSE QDR_ATTEMPTS END QDR_NUM,
      QDR_ATTEMPTS QDR_DEN
  FROM(
SELECT TRUNC(FECHA)   FECHA,
       LNCEL_ID,
       ROUND(CASE WHEN SIGN_CONN_ESTAB_ATT = 0 THEN 1
                  WHEN EPS_BEARER_SETUP_ATTEMPTS = 0 THEN (100*(SIGN_CONN_ESTAB_COMP/SIGN_CONN_ESTAB_ATT))
                                                     ELSE (100*(SIGN_CONN_ESTAB_COMP/SIGN_CONN_ESTAB_ATT) * 
                                                               (EPS_BEARER_SETUP_COMPLETIONS/EPS_BEARER_SETUP_ATTEMPTS)) END, 6) ACCESIBILITY,
       (SIGN_CONN_ESTAB_ATT + 2 * EPS_BEARER_SETUP_ATTEMPTS) QDA_ATTEMPTS,
       ROUND(100*(1- DECODE(QDR_ATTEMPTS,0,0,((EPC_EPS_BEARER_REL_REQ_RNL + EPC_EPS_BEARER_REL_REQ_OTH + ENB_EPS_BEARER_REL_REQ_RNL + 
                                   ENB_EPS_BEARER_REL_REQ_TNL + ENB_EPS_BEARER_REL_REQ_OTH) / QDR_ATTEMPTS))),6) RETAINABILITY,       
       QDR_ATTEMPTS
  FROM(
SELECT A.PERIOD_START_TIME FECHA,
       A.LNCEL_ID,
       SUM(SIGN_CONN_ESTAB_COMP) SIGN_CONN_ESTAB_COMP,
                                              
       SUM(SIGN_CONN_ESTAB_ATT_MO_S + SIGN_CONN_ESTAB_ATT_MT + SIGN_CONN_ESTAB_ATT_MO_D + SIGN_CONN_ESTAB_ATT_OTHERS + 
           SIGN_CONN_ESTAB_ATT_EMG) SIGN_CONN_ESTAB_ATT,
                                                   
       SUM(EPS_BEARER_SETUP_COMPLETIONS) EPS_BEARER_SETUP_COMPLETIONS,
       SUM(EPS_BEARER_SETUP_ATTEMPTS) EPS_BEARER_SETUP_ATTEMPTS,
                                             
       SUM(EPC_EPS_BEARER_REL_REQ_RNL) EPC_EPS_BEARER_REL_REQ_RNL,
       SUM(EPC_EPS_BEARER_REL_REQ_OTH) EPC_EPS_BEARER_REL_REQ_OTH,
       SUM(ENB_EPS_BEARER_REL_REQ_RNL) ENB_EPS_BEARER_REL_REQ_RNL,
       SUM(ENB_EPS_BEARER_REL_REQ_TNL) ENB_EPS_BEARER_REL_REQ_TNL,
       SUM(ENB_EPS_BEARER_REL_REQ_OTH) ENB_EPS_BEARER_REL_REQ_OTH,
                                             
       SUM(EPC_EPS_BEARER_REL_REQ_NORM + EPC_EPS_BEARER_REL_REQ_DETACH + EPC_EPS_BEARER_REL_REQ_RNL + EPC_EPS_BEARER_REL_REQ_OTH +
           ENB_EPSBEAR_REL_REQ_RNL_REDIR + ENB_EPS_BEARER_REL_REQ_NORM + ENB_EPS_BEARER_REL_REQ_RNL + ENB_EPS_BEARER_REL_REQ_TNL + 
           ENB_EPS_BEARER_REL_REQ_OTH + PRE_EMPT_GBR_BEARER + PRE_EMPT_NON_GBR_BEARER) QDR_ATTEMPTS
                                                    
  FROM NOKLTE_PS_LUEST_MNC1_RAW A,
       NOKLTE_PS_LEPSB_MNC1_RAW B
 WHERE A.PERIOD_START_TIME IN (
SELECT FECHA
  FROM CALIDAD_STATUS_REFERENCES
 WHERE FECHA BETWEEN TO_DATE(FECHA_DESDE, 'DD.MM.YYYY')
                 AND TO_DATE(FECHA_HASTA, 'DD.MM.YYYY') + 83999 / 84000
   AND HORA NOT IN ('00', '01', '02', '03', '04', '05', '06', '23')
                                )
   AND A.PERIOD_START_TIME = B.PERIOD_START_TIME
   AND A.LNCEL_ID = B.LNCEL_ID
GROUP BY A.PERIOD_START_TIME,
       A.LNCEL_ID
             )
              )
      )A, OBJECTS_SP_LTE B
 WHERE A.LNCEL_ID = B.LNCEL_ID (+)
   AND B.LNBTS_ID IS NOT NULL
GROUP BY A.FECHA, 
       A.LNCEL_ID,
       B.LNCEL_NAME,
       B.LNBTS_ID,
       B.LNBTS_NAME,
       B.OSSRC,
       B.MERCADO,
       B.PAIS;

TYPE TYP_NQI_DAY IS TABLE OF CUR_NQI_DAY%ROWTYPE INDEX BY BINARY_INTEGER;
 NQI_DAY TYP_NQI_DAY;

 TYPE T_NQI_DAY IS TABLE OF  LTE_NQI_DAY%ROWTYPE INDEX BY PLS_INTEGER;
 LTE_NQI_DA2 T_NQI_DAY;


C_LIMIT PLS_INTEGER := 1000;
PCNT    NUMBER := 0;

BEGIN

-- Open | Fetch | Close

OPEN CUR_NQI_DAY  (P_FECHA_DESDE, P_FECHA_HASTA);

LOOP

FETCH CUR_NQI_DAY BULK COLLECT INTO NQI_DAY LIMIT C_LIMIT;

FOR I IN 1 .. NQI_DAY.COUNT LOOP

  PCNT := PCNT + 1;

LTE_NQI_DA2(I).FECHA                                 := NQI_DAY(I).FECHA          ;
LTE_NQI_DA2(I).LNCEL_ID                              := NQI_DAY(I).LNCEL_ID       ;
LTE_NQI_DA2(I).LNCEL_NAME                            := NQI_DAY(I).LNCEL_NAME     ;
LTE_NQI_DA2(I).LNBTS_ID                              := NQI_DAY(I).LNBTS_ID       ;
LTE_NQI_DA2(I).LNBTS_NAME                            := NQI_DAY(I).LNBTS_NAME     ;
LTE_NQI_DA2(I).OSSRC                                 := NQI_DAY(I).OSSRC          ;
LTE_NQI_DA2(I).MERCADO                               := NQI_DAY(I).MERCADO        ;
LTE_NQI_DA2(I).PAIS                                  := NQI_DAY(I).PAIS           ;
LTE_NQI_DA2(I).QDA_NUM                               := NQI_DAY(I).QDA_NUM        ;
LTE_NQI_DA2(I).QDA_DEN                               := NQI_DAY(I).QDA_DEN        ;
LTE_NQI_DA2(I).QDR_NUM                               := NQI_DAY(I).QDR_NUM        ;
LTE_NQI_DA2(I).QDR_DEN                               := NQI_DAY(I).QDR_DEN        ;

END LOOP;

IF CUR_NQI_DAY%NOTFOUND THEN
 FORALL I IN LTE_NQI_DA2.FIRST .. PCNT
 INSERT INTO LTE_NQI_DAY VALUES LTE_NQI_DA2(I);

   EXIT;
ELSE

   FORALL I IN LTE_NQI_DA2.FIRST .. LTE_NQI_DA2.LAST
   INSERT INTO LTE_NQI_DAY VALUES LTE_NQI_DA2(I);

END IF;

PCNT := 0;

END LOOP;

COMMIT;

END P_LTE_NQI_DAY_INS;
